import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Providers/ThemeProvider";
import Layout from "@/components/Layout/Layout";
import NextTopLoader from "nextjs-toploader";
import SessionProviderWrapper from "@/Providers/SessionProvider";
import { Suspense } from "react";
import Loading from "./loading";
import AuthProvider from "@/Providers/AuthProvider";
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <SessionProviderWrapper>
          <AuthProvider>
            <NextTopLoader color="#3ea53c" height={4} />
            <ThemeProvider attribute="class" defaultTheme="light">
              <Suspense fallback={<Loading />}>
                <Layout>{children}</Layout>
              </Suspense>
            </ThemeProvider>
          </AuthProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
